# tasks/alertmanager.yaml
- name: create folder {{ alertmanager_container_name }}
  ansible.builtin.file:
    path: "{{ alertmanager_dir }}"
    group: "{{ username }}"
    owner: "{{ username }}"
    state: directory

- name: copy template alertmanager to {{ alertmanager_dir }}
  ansible.builtin.template:
    src: templates/alertmanager.yaml.j2
    dest: "{{ alertmanager_dir }}/alertmanager.yaml"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0644"
  notify: restart alertmanager

- name: Create Alertmanager docker-compose file
  ansible.builtin.template:
    src: templates/alertmanager_compose.yaml.j2
    dest: "{{ alertmanager_dir }}/docker-compose.yaml"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0644"
  notify: restart alertmanager

