# blackbox-prod.yaml
- name: Config all server
  hosts: all
  become: true
  vars:
    prometheus_url: prometheus.home-local.site
  roles:
  - common
  - docker
  - grafana-alloy

- name: Config monitoring server
  hosts: monitoring-server
  become: true
  roles:
  - monitoring
  - traefik

- name: Config blackbox server
  hosts: blackbox-server
  become: yes
  vars:
    victoriametrics_url: prometheus.home-local.site
  roles:
  - blackbox-exporter
  - traefik
