# blackbox-stage.yaml
- name: Config blackbox server
  hosts: monitoring-blackbox-server
  become: yes
  roles:
    - common
    - docker
    - monitoring
    - grafana-alloy
    - blackbox-exporter
    - traefik
